// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cloudsdk/protos/message_queue.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageBody   string                 `protobuf:"bytes,2,opt,name=messageBody,proto3" json:"messageBody,omitempty"`
	ReceiptHandle string                 `protobuf:"bytes,3,opt,name=receiptHandle,proto3" json:"receiptHandle,omitempty"`
	QueueUrl      string                 `protobuf:"bytes,4,opt,name=queueUrl,proto3" json:"queueUrl,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageQueue) Reset() {
	*x = MessageQueue{}
	mi := &file_cloudsdk_protos_message_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageQueue) ProtoMessage() {}

func (x *MessageQueue) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsdk_protos_message_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageQueue.ProtoReflect.Descriptor instead.
func (*MessageQueue) Descriptor() ([]byte, []int) {
	return file_cloudsdk_protos_message_queue_proto_rawDescGZIP(), []int{0}
}

func (x *MessageQueue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageQueue) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

func (x *MessageQueue) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

func (x *MessageQueue) GetQueueUrl() string {
	if x != nil {
		return x.QueueUrl
	}
	return ""
}

func (x *MessageQueue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageQueue) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type MessageQueueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageQueue        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageQueueList) Reset() {
	*x = MessageQueueList{}
	mi := &file_cloudsdk_protos_message_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageQueueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageQueueList) ProtoMessage() {}

func (x *MessageQueueList) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsdk_protos_message_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageQueueList.ProtoReflect.Descriptor instead.
func (*MessageQueueList) Descriptor() ([]byte, []int) {
	return file_cloudsdk_protos_message_queue_proto_rawDescGZIP(), []int{1}
}

func (x *MessageQueueList) GetMessages() []*MessageQueue {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_cloudsdk_protos_message_queue_proto protoreflect.FileDescriptor

const file_cloudsdk_protos_message_queue_proto_rawDesc = "" +
	"\n" +
	"#cloudsdk/protos/message_queue.proto\x12\x06protos\"\xbc\x01\n" +
	"\fMessageQueue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vmessageBody\x18\x02 \x01(\tR\vmessageBody\x12$\n" +
	"\rreceiptHandle\x18\x03 \x01(\tR\rreceiptHandle\x12\x1a\n" +
	"\bqueueUrl\x18\x04 \x01(\tR\bqueueUrl\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\"D\n" +
	"\x10MessageQueueList\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.protos.MessageQueueR\bmessagesB\x11Z\x0fcloudsdk/protosb\x06proto3"

var (
	file_cloudsdk_protos_message_queue_proto_rawDescOnce sync.Once
	file_cloudsdk_protos_message_queue_proto_rawDescData []byte
)

func file_cloudsdk_protos_message_queue_proto_rawDescGZIP() []byte {
	file_cloudsdk_protos_message_queue_proto_rawDescOnce.Do(func() {
		file_cloudsdk_protos_message_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloudsdk_protos_message_queue_proto_rawDesc), len(file_cloudsdk_protos_message_queue_proto_rawDesc)))
	})
	return file_cloudsdk_protos_message_queue_proto_rawDescData
}

var file_cloudsdk_protos_message_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cloudsdk_protos_message_queue_proto_goTypes = []any{
	(*MessageQueue)(nil),     // 0: protos.MessageQueue
	(*MessageQueueList)(nil), // 1: protos.MessageQueueList
}
var file_cloudsdk_protos_message_queue_proto_depIdxs = []int32{
	0, // 0: protos.MessageQueueList.messages:type_name -> protos.MessageQueue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cloudsdk_protos_message_queue_proto_init() }
func file_cloudsdk_protos_message_queue_proto_init() {
	if File_cloudsdk_protos_message_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloudsdk_protos_message_queue_proto_rawDesc), len(file_cloudsdk_protos_message_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloudsdk_protos_message_queue_proto_goTypes,
		DependencyIndexes: file_cloudsdk_protos_message_queue_proto_depIdxs,
		MessageInfos:      file_cloudsdk_protos_message_queue_proto_msgTypes,
	}.Build()
	File_cloudsdk_protos_message_queue_proto = out.File
	file_cloudsdk_protos_message_queue_proto_goTypes = nil
	file_cloudsdk_protos_message_queue_proto_depIdxs = nil
}
