// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloudsdk/protos/message_queue.proto
// Protobuf Java Version: 4.29.3

package protos;

public final class MessageQueueOuterClass {
  private MessageQueueOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageQueueOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageQueueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.MessageQueue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string messageBody = 2;</code>
     * @return The messageBody.
     */
    java.lang.String getMessageBody();
    /**
     * <code>string messageBody = 2;</code>
     * @return The bytes for messageBody.
     */
    com.google.protobuf.ByteString
        getMessageBodyBytes();

    /**
     * <code>string receiptHandle = 3;</code>
     * @return The receiptHandle.
     */
    java.lang.String getReceiptHandle();
    /**
     * <code>string receiptHandle = 3;</code>
     * @return The bytes for receiptHandle.
     */
    com.google.protobuf.ByteString
        getReceiptHandleBytes();

    /**
     * <code>string queueUrl = 4;</code>
     * @return The queueUrl.
     */
    java.lang.String getQueueUrl();
    /**
     * <code>string queueUrl = 4;</code>
     * @return The bytes for queueUrl.
     */
    com.google.protobuf.ByteString
        getQueueUrlBytes();

    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string provider = 6;</code>
     * @return The provider.
     */
    java.lang.String getProvider();
    /**
     * <code>string provider = 6;</code>
     * @return The bytes for provider.
     */
    com.google.protobuf.ByteString
        getProviderBytes();
  }
  /**
   * Protobuf type {@code protos.MessageQueue}
   */
  public static final class MessageQueue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.MessageQueue)
      MessageQueueOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MessageQueue.class.getName());
    }
    // Use MessageQueue.newBuilder() to construct.
    private MessageQueue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MessageQueue() {
      id_ = "";
      messageBody_ = "";
      receiptHandle_ = "";
      queueUrl_ = "";
      provider_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.MessageQueueOuterClass.internal_static_protos_MessageQueue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.MessageQueueOuterClass.internal_static_protos_MessageQueue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.MessageQueueOuterClass.MessageQueue.class, protos.MessageQueueOuterClass.MessageQueue.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBODY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageBody_ = "";
    /**
     * <code>string messageBody = 2;</code>
     * @return The messageBody.
     */
    @java.lang.Override
    public java.lang.String getMessageBody() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageBody_ = s;
        return s;
      }
    }
    /**
     * <code>string messageBody = 2;</code>
     * @return The bytes for messageBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBodyBytes() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIPTHANDLE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object receiptHandle_ = "";
    /**
     * <code>string receiptHandle = 3;</code>
     * @return The receiptHandle.
     */
    @java.lang.Override
    public java.lang.String getReceiptHandle() {
      java.lang.Object ref = receiptHandle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiptHandle_ = s;
        return s;
      }
    }
    /**
     * <code>string receiptHandle = 3;</code>
     * @return The bytes for receiptHandle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiptHandleBytes() {
      java.lang.Object ref = receiptHandle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiptHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUEUEURL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object queueUrl_ = "";
    /**
     * <code>string queueUrl = 4;</code>
     * @return The queueUrl.
     */
    @java.lang.Override
    public java.lang.String getQueueUrl() {
      java.lang.Object ref = queueUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queueUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string queueUrl = 4;</code>
     * @return The bytes for queueUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueueUrlBytes() {
      java.lang.Object ref = queueUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PROVIDER_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object provider_ = "";
    /**
     * <code>string provider = 6;</code>
     * @return The provider.
     */
    @java.lang.Override
    public java.lang.String getProvider() {
      java.lang.Object ref = provider_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        provider_ = s;
        return s;
      }
    }
    /**
     * <code>string provider = 6;</code>
     * @return The bytes for provider.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProviderBytes() {
      java.lang.Object ref = provider_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provider_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageBody_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, messageBody_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiptHandle_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, receiptHandle_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueUrl_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, queueUrl_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(provider_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, provider_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageBody_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, messageBody_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiptHandle_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, receiptHandle_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueUrl_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, queueUrl_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(provider_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, provider_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.MessageQueueOuterClass.MessageQueue)) {
        return super.equals(obj);
      }
      protos.MessageQueueOuterClass.MessageQueue other = (protos.MessageQueueOuterClass.MessageQueue) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getMessageBody()
          .equals(other.getMessageBody())) return false;
      if (!getReceiptHandle()
          .equals(other.getReceiptHandle())) return false;
      if (!getQueueUrl()
          .equals(other.getQueueUrl())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getProvider()
          .equals(other.getProvider())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MESSAGEBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBody().hashCode();
      hash = (37 * hash) + RECEIPTHANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiptHandle().hashCode();
      hash = (37 * hash) + QUEUEURL_FIELD_NUMBER;
      hash = (53 * hash) + getQueueUrl().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + PROVIDER_FIELD_NUMBER;
      hash = (53 * hash) + getProvider().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protos.MessageQueueOuterClass.MessageQueue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protos.MessageQueueOuterClass.MessageQueue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MessageQueueOuterClass.MessageQueue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.MessageQueueOuterClass.MessageQueue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.MessageQueue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.MessageQueue)
        protos.MessageQueueOuterClass.MessageQueueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.MessageQueueOuterClass.internal_static_protos_MessageQueue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.MessageQueueOuterClass.internal_static_protos_MessageQueue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.MessageQueueOuterClass.MessageQueue.class, protos.MessageQueueOuterClass.MessageQueue.Builder.class);
      }

      // Construct using protos.MessageQueueOuterClass.MessageQueue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        messageBody_ = "";
        receiptHandle_ = "";
        queueUrl_ = "";
        timestamp_ = 0L;
        provider_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.MessageQueueOuterClass.internal_static_protos_MessageQueue_descriptor;
      }

      @java.lang.Override
      public protos.MessageQueueOuterClass.MessageQueue getDefaultInstanceForType() {
        return protos.MessageQueueOuterClass.MessageQueue.getDefaultInstance();
      }

      @java.lang.Override
      public protos.MessageQueueOuterClass.MessageQueue build() {
        protos.MessageQueueOuterClass.MessageQueue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.MessageQueueOuterClass.MessageQueue buildPartial() {
        protos.MessageQueueOuterClass.MessageQueue result = new protos.MessageQueueOuterClass.MessageQueue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protos.MessageQueueOuterClass.MessageQueue result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.messageBody_ = messageBody_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.receiptHandle_ = receiptHandle_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.queueUrl_ = queueUrl_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.provider_ = provider_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.MessageQueueOuterClass.MessageQueue) {
          return mergeFrom((protos.MessageQueueOuterClass.MessageQueue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.MessageQueueOuterClass.MessageQueue other) {
        if (other == protos.MessageQueueOuterClass.MessageQueue.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMessageBody().isEmpty()) {
          messageBody_ = other.messageBody_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getReceiptHandle().isEmpty()) {
          receiptHandle_ = other.receiptHandle_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getQueueUrl().isEmpty()) {
          queueUrl_ = other.queueUrl_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getProvider().isEmpty()) {
          provider_ = other.provider_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                messageBody_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                receiptHandle_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                queueUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                provider_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object messageBody_ = "";
      /**
       * <code>string messageBody = 2;</code>
       * @return The messageBody.
       */
      public java.lang.String getMessageBody() {
        java.lang.Object ref = messageBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageBody = 2;</code>
       * @return The bytes for messageBody.
       */
      public com.google.protobuf.ByteString
          getMessageBodyBytes() {
        java.lang.Object ref = messageBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageBody = 2;</code>
       * @param value The messageBody to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBody(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageBody_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string messageBody = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageBody() {
        messageBody_ = getDefaultInstance().getMessageBody();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string messageBody = 2;</code>
       * @param value The bytes for messageBody to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        messageBody_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object receiptHandle_ = "";
      /**
       * <code>string receiptHandle = 3;</code>
       * @return The receiptHandle.
       */
      public java.lang.String getReceiptHandle() {
        java.lang.Object ref = receiptHandle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiptHandle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @return The bytes for receiptHandle.
       */
      public com.google.protobuf.ByteString
          getReceiptHandleBytes() {
        java.lang.Object ref = receiptHandle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiptHandle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @param value The receiptHandle to set.
       * @return This builder for chaining.
       */
      public Builder setReceiptHandle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        receiptHandle_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiptHandle() {
        receiptHandle_ = getDefaultInstance().getReceiptHandle();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @param value The bytes for receiptHandle to set.
       * @return This builder for chaining.
       */
      public Builder setReceiptHandleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        receiptHandle_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object queueUrl_ = "";
      /**
       * <code>string queueUrl = 4;</code>
       * @return The queueUrl.
       */
      public java.lang.String getQueueUrl() {
        java.lang.Object ref = queueUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          queueUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @return The bytes for queueUrl.
       */
      public com.google.protobuf.ByteString
          getQueueUrlBytes() {
        java.lang.Object ref = queueUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queueUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @param value The queueUrl to set.
       * @return This builder for chaining.
       */
      public Builder setQueueUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        queueUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueueUrl() {
        queueUrl_ = getDefaultInstance().getQueueUrl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @param value The bytes for queueUrl to set.
       * @return This builder for chaining.
       */
      public Builder setQueueUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        queueUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 5;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object provider_ = "";
      /**
       * <code>string provider = 6;</code>
       * @return The provider.
       */
      public java.lang.String getProvider() {
        java.lang.Object ref = provider_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          provider_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string provider = 6;</code>
       * @return The bytes for provider.
       */
      public com.google.protobuf.ByteString
          getProviderBytes() {
        java.lang.Object ref = provider_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provider_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provider = 6;</code>
       * @param value The provider to set.
       * @return This builder for chaining.
       */
      public Builder setProvider(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        provider_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string provider = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearProvider() {
        provider_ = getDefaultInstance().getProvider();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string provider = 6;</code>
       * @param value The bytes for provider to set.
       * @return This builder for chaining.
       */
      public Builder setProviderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        provider_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.MessageQueue)
    }

    // @@protoc_insertion_point(class_scope:protos.MessageQueue)
    private static final protos.MessageQueueOuterClass.MessageQueue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.MessageQueueOuterClass.MessageQueue();
    }

    public static protos.MessageQueueOuterClass.MessageQueue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageQueue>
        PARSER = new com.google.protobuf.AbstractParser<MessageQueue>() {
      @java.lang.Override
      public MessageQueue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageQueue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageQueue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.MessageQueueOuterClass.MessageQueue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageQueueListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.MessageQueueList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    java.util.List<protos.MessageQueueOuterClass.MessageQueue> 
        getMessagesList();
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    protos.MessageQueueOuterClass.MessageQueue getMessages(int index);
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    java.util.List<? extends protos.MessageQueueOuterClass.MessageQueueOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    protos.MessageQueueOuterClass.MessageQueueOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.MessageQueueList}
   */
  public static final class MessageQueueList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.MessageQueueList)
      MessageQueueListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MessageQueueList.class.getName());
    }
    // Use MessageQueueList.newBuilder() to construct.
    private MessageQueueList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MessageQueueList() {
      messages_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.MessageQueueOuterClass.internal_static_protos_MessageQueueList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.MessageQueueOuterClass.internal_static_protos_MessageQueueList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.MessageQueueOuterClass.MessageQueueList.class, protos.MessageQueueOuterClass.MessageQueueList.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<protos.MessageQueueOuterClass.MessageQueue> messages_;
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<protos.MessageQueueOuterClass.MessageQueue> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protos.MessageQueueOuterClass.MessageQueueOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    @java.lang.Override
    public protos.MessageQueueOuterClass.MessageQueue getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .protos.MessageQueue messages = 1;</code>
     */
    @java.lang.Override
    public protos.MessageQueueOuterClass.MessageQueueOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.MessageQueueOuterClass.MessageQueueList)) {
        return super.equals(obj);
      }
      protos.MessageQueueOuterClass.MessageQueueList other = (protos.MessageQueueOuterClass.MessageQueueList) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protos.MessageQueueOuterClass.MessageQueueList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protos.MessageQueueOuterClass.MessageQueueList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MessageQueueOuterClass.MessageQueueList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.MessageQueueOuterClass.MessageQueueList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.MessageQueueList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.MessageQueueList)
        protos.MessageQueueOuterClass.MessageQueueListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.MessageQueueOuterClass.internal_static_protos_MessageQueueList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.MessageQueueOuterClass.internal_static_protos_MessageQueueList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.MessageQueueOuterClass.MessageQueueList.class, protos.MessageQueueOuterClass.MessageQueueList.Builder.class);
      }

      // Construct using protos.MessageQueueOuterClass.MessageQueueList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
        } else {
          messages_ = null;
          messagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.MessageQueueOuterClass.internal_static_protos_MessageQueueList_descriptor;
      }

      @java.lang.Override
      public protos.MessageQueueOuterClass.MessageQueueList getDefaultInstanceForType() {
        return protos.MessageQueueOuterClass.MessageQueueList.getDefaultInstance();
      }

      @java.lang.Override
      public protos.MessageQueueOuterClass.MessageQueueList build() {
        protos.MessageQueueOuterClass.MessageQueueList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.MessageQueueOuterClass.MessageQueueList buildPartial() {
        protos.MessageQueueOuterClass.MessageQueueList result = new protos.MessageQueueOuterClass.MessageQueueList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(protos.MessageQueueOuterClass.MessageQueueList result) {
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
      }

      private void buildPartial0(protos.MessageQueueOuterClass.MessageQueueList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.MessageQueueOuterClass.MessageQueueList) {
          return mergeFrom((protos.MessageQueueOuterClass.MessageQueueList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.MessageQueueOuterClass.MessageQueueList other) {
        if (other == protos.MessageQueueOuterClass.MessageQueueList.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                protos.MessageQueueOuterClass.MessageQueue m =
                    input.readMessage(
                        protos.MessageQueueOuterClass.MessageQueue.parser(),
                        extensionRegistry);
                if (messagesBuilder_ == null) {
                  ensureMessagesIsMutable();
                  messages_.add(m);
                } else {
                  messagesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.MessageQueueOuterClass.MessageQueue> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<protos.MessageQueueOuterClass.MessageQueue>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protos.MessageQueueOuterClass.MessageQueue, protos.MessageQueueOuterClass.MessageQueue.Builder, protos.MessageQueueOuterClass.MessageQueueOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public java.util.List<protos.MessageQueueOuterClass.MessageQueue> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public protos.MessageQueueOuterClass.MessageQueue getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder setMessages(
          int index, protos.MessageQueueOuterClass.MessageQueue value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder setMessages(
          int index, protos.MessageQueueOuterClass.MessageQueue.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder addMessages(protos.MessageQueueOuterClass.MessageQueue value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder addMessages(
          int index, protos.MessageQueueOuterClass.MessageQueue value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder addMessages(
          protos.MessageQueueOuterClass.MessageQueue.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder addMessages(
          int index, protos.MessageQueueOuterClass.MessageQueue.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends protos.MessageQueueOuterClass.MessageQueue> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public protos.MessageQueueOuterClass.MessageQueue.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public protos.MessageQueueOuterClass.MessageQueueOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public java.util.List<? extends protos.MessageQueueOuterClass.MessageQueueOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public protos.MessageQueueOuterClass.MessageQueue.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            protos.MessageQueueOuterClass.MessageQueue.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public protos.MessageQueueOuterClass.MessageQueue.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, protos.MessageQueueOuterClass.MessageQueue.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.MessageQueue messages = 1;</code>
       */
      public java.util.List<protos.MessageQueueOuterClass.MessageQueue.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protos.MessageQueueOuterClass.MessageQueue, protos.MessageQueueOuterClass.MessageQueue.Builder, protos.MessageQueueOuterClass.MessageQueueOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protos.MessageQueueOuterClass.MessageQueue, protos.MessageQueueOuterClass.MessageQueue.Builder, protos.MessageQueueOuterClass.MessageQueueOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protos.MessageQueueList)
    }

    // @@protoc_insertion_point(class_scope:protos.MessageQueueList)
    private static final protos.MessageQueueOuterClass.MessageQueueList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.MessageQueueOuterClass.MessageQueueList();
    }

    public static protos.MessageQueueOuterClass.MessageQueueList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageQueueList>
        PARSER = new com.google.protobuf.AbstractParser<MessageQueueList>() {
      @java.lang.Override
      public MessageQueueList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageQueueList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageQueueList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.MessageQueueOuterClass.MessageQueueList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_MessageQueue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_MessageQueue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_MessageQueueList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_MessageQueueList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#cloudsdk/protos/message_queue.proto\022\006p" +
      "rotos\"}\n\014MessageQueue\022\n\n\002id\030\001 \001(\t\022\023\n\013mes" +
      "sageBody\030\002 \001(\t\022\025\n\rreceiptHandle\030\003 \001(\t\022\020\n" +
      "\010queueUrl\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\003\022\020\n\010pr" +
      "ovider\030\006 \001(\t\":\n\020MessageQueueList\022&\n\010mess" +
      "ages\030\001 \003(\0132\024.protos.MessageQueueB\021Z\017clou" +
      "dsdk/protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_MessageQueue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_MessageQueue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_MessageQueue_descriptor,
        new java.lang.String[] { "Id", "MessageBody", "ReceiptHandle", "QueueUrl", "Timestamp", "Provider", });
    internal_static_protos_MessageQueueList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_MessageQueueList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_MessageQueueList_descriptor,
        new java.lang.String[] { "Messages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
