// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: event_sqs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SQSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageBody   string                 `protobuf:"bytes,2,opt,name=messageBody,proto3" json:"messageBody,omitempty"`
	ReceiptHandle string                 `protobuf:"bytes,3,opt,name=receiptHandle,proto3" json:"receiptHandle,omitempty"`
	QueueUrl      string                 `protobuf:"bytes,4,opt,name=queueUrl,proto3" json:"queueUrl,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQSMessage) Reset() {
	*x = SQSMessage{}
	mi := &file_event_sqs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSMessage) ProtoMessage() {}

func (x *SQSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_event_sqs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSMessage.ProtoReflect.Descriptor instead.
func (*SQSMessage) Descriptor() ([]byte, []int) {
	return file_event_sqs_proto_rawDescGZIP(), []int{0}
}

func (x *SQSMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SQSMessage) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

func (x *SQSMessage) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

func (x *SQSMessage) GetQueueUrl() string {
	if x != nil {
		return x.QueueUrl
	}
	return ""
}

func (x *SQSMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SQSMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SQSMessage          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQSMessageList) Reset() {
	*x = SQSMessageList{}
	mi := &file_event_sqs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQSMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSMessageList) ProtoMessage() {}

func (x *SQSMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_event_sqs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSMessageList.ProtoReflect.Descriptor instead.
func (*SQSMessageList) Descriptor() ([]byte, []int) {
	return file_event_sqs_proto_rawDescGZIP(), []int{1}
}

func (x *SQSMessageList) GetMessages() []*SQSMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_event_sqs_proto protoreflect.FileDescriptor

const file_event_sqs_proto_rawDesc = "" +
	"\n" +
	"\x0fevent_sqs.proto\x12\x06protos\"\x9e\x01\n" +
	"\n" +
	"SQSMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vmessageBody\x18\x02 \x01(\tR\vmessageBody\x12$\n" +
	"\rreceiptHandle\x18\x03 \x01(\tR\rreceiptHandle\x12\x1a\n" +
	"\bqueueUrl\x18\x04 \x01(\tR\bqueueUrl\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"@\n" +
	"\x0eSQSMessageList\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.protos.SQSMessageR\bmessagesB\fZ\n" +
	"fii/protosb\x06proto3"

var (
	file_event_sqs_proto_rawDescOnce sync.Once
	file_event_sqs_proto_rawDescData []byte
)

func file_event_sqs_proto_rawDescGZIP() []byte {
	file_event_sqs_proto_rawDescOnce.Do(func() {
		file_event_sqs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_sqs_proto_rawDesc), len(file_event_sqs_proto_rawDesc)))
	})
	return file_event_sqs_proto_rawDescData
}

var file_event_sqs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_sqs_proto_goTypes = []any{
	(*SQSMessage)(nil),     // 0: protos.SQSMessage
	(*SQSMessageList)(nil), // 1: protos.SQSMessageList
}
var file_event_sqs_proto_depIdxs = []int32{
	0, // 0: protos.SQSMessageList.messages:type_name -> protos.SQSMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_sqs_proto_init() }
func file_event_sqs_proto_init() {
	if File_event_sqs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_sqs_proto_rawDesc), len(file_event_sqs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_sqs_proto_goTypes,
		DependencyIndexes: file_event_sqs_proto_depIdxs,
		MessageInfos:      file_event_sqs_proto_msgTypes,
	}.Build()
	File_event_sqs_proto = out.File
	file_event_sqs_proto_goTypes = nil
	file_event_sqs_proto_depIdxs = nil
}
