// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event_sqs.proto
// Protobuf Java Version: 4.29.3

package protos;

public final class EventSqs {
  private EventSqs() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      EventSqs.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SQSMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.SQSMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string messageBody = 2;</code>
     * @return The messageBody.
     */
    java.lang.String getMessageBody();
    /**
     * <code>string messageBody = 2;</code>
     * @return The bytes for messageBody.
     */
    com.google.protobuf.ByteString
        getMessageBodyBytes();

    /**
     * <code>string receiptHandle = 3;</code>
     * @return The receiptHandle.
     */
    java.lang.String getReceiptHandle();
    /**
     * <code>string receiptHandle = 3;</code>
     * @return The bytes for receiptHandle.
     */
    com.google.protobuf.ByteString
        getReceiptHandleBytes();

    /**
     * <code>string queueUrl = 4;</code>
     * @return The queueUrl.
     */
    java.lang.String getQueueUrl();
    /**
     * <code>string queueUrl = 4;</code>
     * @return The bytes for queueUrl.
     */
    com.google.protobuf.ByteString
        getQueueUrlBytes();

    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code protos.SQSMessage}
   */
  public static final class SQSMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.SQSMessage)
      SQSMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SQSMessage.class.getName());
    }
    // Use SQSMessage.newBuilder() to construct.
    private SQSMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SQSMessage() {
      id_ = "";
      messageBody_ = "";
      receiptHandle_ = "";
      queueUrl_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.EventSqs.internal_static_protos_SQSMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.EventSqs.internal_static_protos_SQSMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.EventSqs.SQSMessage.class, protos.EventSqs.SQSMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBODY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageBody_ = "";
    /**
     * <code>string messageBody = 2;</code>
     * @return The messageBody.
     */
    @java.lang.Override
    public java.lang.String getMessageBody() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageBody_ = s;
        return s;
      }
    }
    /**
     * <code>string messageBody = 2;</code>
     * @return The bytes for messageBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBodyBytes() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIPTHANDLE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object receiptHandle_ = "";
    /**
     * <code>string receiptHandle = 3;</code>
     * @return The receiptHandle.
     */
    @java.lang.Override
    public java.lang.String getReceiptHandle() {
      java.lang.Object ref = receiptHandle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiptHandle_ = s;
        return s;
      }
    }
    /**
     * <code>string receiptHandle = 3;</code>
     * @return The bytes for receiptHandle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiptHandleBytes() {
      java.lang.Object ref = receiptHandle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiptHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUEUEURL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object queueUrl_ = "";
    /**
     * <code>string queueUrl = 4;</code>
     * @return The queueUrl.
     */
    @java.lang.Override
    public java.lang.String getQueueUrl() {
      java.lang.Object ref = queueUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queueUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string queueUrl = 4;</code>
     * @return The bytes for queueUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueueUrlBytes() {
      java.lang.Object ref = queueUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageBody_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, messageBody_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiptHandle_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, receiptHandle_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueUrl_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, queueUrl_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageBody_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, messageBody_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiptHandle_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, receiptHandle_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueUrl_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, queueUrl_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.EventSqs.SQSMessage)) {
        return super.equals(obj);
      }
      protos.EventSqs.SQSMessage other = (protos.EventSqs.SQSMessage) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getMessageBody()
          .equals(other.getMessageBody())) return false;
      if (!getReceiptHandle()
          .equals(other.getReceiptHandle())) return false;
      if (!getQueueUrl()
          .equals(other.getQueueUrl())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MESSAGEBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBody().hashCode();
      hash = (37 * hash) + RECEIPTHANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiptHandle().hashCode();
      hash = (37 * hash) + QUEUEURL_FIELD_NUMBER;
      hash = (53 * hash) + getQueueUrl().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.EventSqs.SQSMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protos.EventSqs.SQSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protos.EventSqs.SQSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.EventSqs.SQSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.EventSqs.SQSMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.SQSMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.SQSMessage)
        protos.EventSqs.SQSMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.EventSqs.internal_static_protos_SQSMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.EventSqs.internal_static_protos_SQSMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.EventSqs.SQSMessage.class, protos.EventSqs.SQSMessage.Builder.class);
      }

      // Construct using protos.EventSqs.SQSMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        messageBody_ = "";
        receiptHandle_ = "";
        queueUrl_ = "";
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.EventSqs.internal_static_protos_SQSMessage_descriptor;
      }

      @java.lang.Override
      public protos.EventSqs.SQSMessage getDefaultInstanceForType() {
        return protos.EventSqs.SQSMessage.getDefaultInstance();
      }

      @java.lang.Override
      public protos.EventSqs.SQSMessage build() {
        protos.EventSqs.SQSMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.EventSqs.SQSMessage buildPartial() {
        protos.EventSqs.SQSMessage result = new protos.EventSqs.SQSMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protos.EventSqs.SQSMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.messageBody_ = messageBody_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.receiptHandle_ = receiptHandle_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.queueUrl_ = queueUrl_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.EventSqs.SQSMessage) {
          return mergeFrom((protos.EventSqs.SQSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.EventSqs.SQSMessage other) {
        if (other == protos.EventSqs.SQSMessage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMessageBody().isEmpty()) {
          messageBody_ = other.messageBody_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getReceiptHandle().isEmpty()) {
          receiptHandle_ = other.receiptHandle_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getQueueUrl().isEmpty()) {
          queueUrl_ = other.queueUrl_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                messageBody_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                receiptHandle_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                queueUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object messageBody_ = "";
      /**
       * <code>string messageBody = 2;</code>
       * @return The messageBody.
       */
      public java.lang.String getMessageBody() {
        java.lang.Object ref = messageBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageBody = 2;</code>
       * @return The bytes for messageBody.
       */
      public com.google.protobuf.ByteString
          getMessageBodyBytes() {
        java.lang.Object ref = messageBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageBody = 2;</code>
       * @param value The messageBody to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBody(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageBody_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string messageBody = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageBody() {
        messageBody_ = getDefaultInstance().getMessageBody();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string messageBody = 2;</code>
       * @param value The bytes for messageBody to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        messageBody_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object receiptHandle_ = "";
      /**
       * <code>string receiptHandle = 3;</code>
       * @return The receiptHandle.
       */
      public java.lang.String getReceiptHandle() {
        java.lang.Object ref = receiptHandle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiptHandle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @return The bytes for receiptHandle.
       */
      public com.google.protobuf.ByteString
          getReceiptHandleBytes() {
        java.lang.Object ref = receiptHandle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiptHandle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @param value The receiptHandle to set.
       * @return This builder for chaining.
       */
      public Builder setReceiptHandle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        receiptHandle_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiptHandle() {
        receiptHandle_ = getDefaultInstance().getReceiptHandle();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string receiptHandle = 3;</code>
       * @param value The bytes for receiptHandle to set.
       * @return This builder for chaining.
       */
      public Builder setReceiptHandleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        receiptHandle_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object queueUrl_ = "";
      /**
       * <code>string queueUrl = 4;</code>
       * @return The queueUrl.
       */
      public java.lang.String getQueueUrl() {
        java.lang.Object ref = queueUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          queueUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @return The bytes for queueUrl.
       */
      public com.google.protobuf.ByteString
          getQueueUrlBytes() {
        java.lang.Object ref = queueUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queueUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @param value The queueUrl to set.
       * @return This builder for chaining.
       */
      public Builder setQueueUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        queueUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueueUrl() {
        queueUrl_ = getDefaultInstance().getQueueUrl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string queueUrl = 4;</code>
       * @param value The bytes for queueUrl to set.
       * @return This builder for chaining.
       */
      public Builder setQueueUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        queueUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 5;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.SQSMessage)
    }

    // @@protoc_insertion_point(class_scope:protos.SQSMessage)
    private static final protos.EventSqs.SQSMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.EventSqs.SQSMessage();
    }

    public static protos.EventSqs.SQSMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SQSMessage>
        PARSER = new com.google.protobuf.AbstractParser<SQSMessage>() {
      @java.lang.Override
      public SQSMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SQSMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SQSMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.EventSqs.SQSMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SQSMessageListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.SQSMessageList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    java.util.List<protos.EventSqs.SQSMessage> 
        getMessagesList();
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    protos.EventSqs.SQSMessage getMessages(int index);
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    java.util.List<? extends protos.EventSqs.SQSMessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    protos.EventSqs.SQSMessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.SQSMessageList}
   */
  public static final class SQSMessageList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.SQSMessageList)
      SQSMessageListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SQSMessageList.class.getName());
    }
    // Use SQSMessageList.newBuilder() to construct.
    private SQSMessageList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SQSMessageList() {
      messages_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.EventSqs.internal_static_protos_SQSMessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.EventSqs.internal_static_protos_SQSMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.EventSqs.SQSMessageList.class, protos.EventSqs.SQSMessageList.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<protos.EventSqs.SQSMessage> messages_;
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<protos.EventSqs.SQSMessage> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protos.EventSqs.SQSMessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    @java.lang.Override
    public protos.EventSqs.SQSMessage getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .protos.SQSMessage messages = 1;</code>
     */
    @java.lang.Override
    public protos.EventSqs.SQSMessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.EventSqs.SQSMessageList)) {
        return super.equals(obj);
      }
      protos.EventSqs.SQSMessageList other = (protos.EventSqs.SQSMessageList) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.EventSqs.SQSMessageList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protos.EventSqs.SQSMessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protos.EventSqs.SQSMessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.EventSqs.SQSMessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.EventSqs.SQSMessageList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.SQSMessageList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.SQSMessageList)
        protos.EventSqs.SQSMessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.EventSqs.internal_static_protos_SQSMessageList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.EventSqs.internal_static_protos_SQSMessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.EventSqs.SQSMessageList.class, protos.EventSqs.SQSMessageList.Builder.class);
      }

      // Construct using protos.EventSqs.SQSMessageList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
        } else {
          messages_ = null;
          messagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.EventSqs.internal_static_protos_SQSMessageList_descriptor;
      }

      @java.lang.Override
      public protos.EventSqs.SQSMessageList getDefaultInstanceForType() {
        return protos.EventSqs.SQSMessageList.getDefaultInstance();
      }

      @java.lang.Override
      public protos.EventSqs.SQSMessageList build() {
        protos.EventSqs.SQSMessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.EventSqs.SQSMessageList buildPartial() {
        protos.EventSqs.SQSMessageList result = new protos.EventSqs.SQSMessageList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(protos.EventSqs.SQSMessageList result) {
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
      }

      private void buildPartial0(protos.EventSqs.SQSMessageList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.EventSqs.SQSMessageList) {
          return mergeFrom((protos.EventSqs.SQSMessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.EventSqs.SQSMessageList other) {
        if (other == protos.EventSqs.SQSMessageList.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                protos.EventSqs.SQSMessage m =
                    input.readMessage(
                        protos.EventSqs.SQSMessage.parser(),
                        extensionRegistry);
                if (messagesBuilder_ == null) {
                  ensureMessagesIsMutable();
                  messages_.add(m);
                } else {
                  messagesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.EventSqs.SQSMessage> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<protos.EventSqs.SQSMessage>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protos.EventSqs.SQSMessage, protos.EventSqs.SQSMessage.Builder, protos.EventSqs.SQSMessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public java.util.List<protos.EventSqs.SQSMessage> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public protos.EventSqs.SQSMessage getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, protos.EventSqs.SQSMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, protos.EventSqs.SQSMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder addMessages(protos.EventSqs.SQSMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, protos.EventSqs.SQSMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder addMessages(
          protos.EventSqs.SQSMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, protos.EventSqs.SQSMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends protos.EventSqs.SQSMessage> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public protos.EventSqs.SQSMessage.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public protos.EventSqs.SQSMessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public java.util.List<? extends protos.EventSqs.SQSMessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public protos.EventSqs.SQSMessage.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            protos.EventSqs.SQSMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public protos.EventSqs.SQSMessage.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, protos.EventSqs.SQSMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.SQSMessage messages = 1;</code>
       */
      public java.util.List<protos.EventSqs.SQSMessage.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protos.EventSqs.SQSMessage, protos.EventSqs.SQSMessage.Builder, protos.EventSqs.SQSMessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protos.EventSqs.SQSMessage, protos.EventSqs.SQSMessage.Builder, protos.EventSqs.SQSMessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protos.SQSMessageList)
    }

    // @@protoc_insertion_point(class_scope:protos.SQSMessageList)
    private static final protos.EventSqs.SQSMessageList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.EventSqs.SQSMessageList();
    }

    public static protos.EventSqs.SQSMessageList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SQSMessageList>
        PARSER = new com.google.protobuf.AbstractParser<SQSMessageList>() {
      @java.lang.Override
      public SQSMessageList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SQSMessageList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SQSMessageList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.EventSqs.SQSMessageList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_SQSMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_SQSMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_SQSMessageList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_SQSMessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017event_sqs.proto\022\006protos\"i\n\nSQSMessage\022" +
      "\n\n\002id\030\001 \001(\t\022\023\n\013messageBody\030\002 \001(\t\022\025\n\rrece" +
      "iptHandle\030\003 \001(\t\022\020\n\010queueUrl\030\004 \001(\t\022\021\n\ttim" +
      "estamp\030\005 \001(\003\"6\n\016SQSMessageList\022$\n\010messag" +
      "es\030\001 \003(\0132\022.protos.SQSMessageB\014Z\nfii/prot" +
      "osb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_SQSMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_SQSMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_SQSMessage_descriptor,
        new java.lang.String[] { "Id", "MessageBody", "ReceiptHandle", "QueueUrl", "Timestamp", });
    internal_static_protos_SQSMessageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_SQSMessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_SQSMessageList_descriptor,
        new java.lang.String[] { "Messages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
